/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TrackRouteImport } from './routes/track'
import { Route as VisualizerRouteImport } from './routes/visualizer'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as InfoIdRouteImport } from './routes/info.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileAddressesRouteImport } from './routes/profile.addresses'
import { Route as ProfileOrdersRouteImport } from './routes/profile.orders'
import { Route as AdminProductsSlugRouteImport } from './routes/admin.products.$slug'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizerRoute = VisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/admin/catalog',
  path: '/admin/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoIdRoute = InfoIdRouteImport.update({
  id: '/info/$id',
  path: '/info/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/profile/addresses',
  path: '/profile/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileOrdersRoute = ProfileOrdersRouteImport.update({
  id: '/profile/orders',
  path: '/profile/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsSlugRoute = AdminProductsSlugRouteImport.update({
  id: '/admin/products/$slug',
  path: '/admin/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/visualizer': typeof VisualizerRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/info/$id': typeof InfoIdRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/visualizer': typeof VisualizerRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/info/$id': typeof InfoIdRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/visualizer': typeof VisualizerRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/info/$id': typeof InfoIdRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/track'
    | '/visualizer'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/info/$id'
    | '/order/$id'
    | '/products/$slug'
    | '/profile/addresses'
    | '/profile/orders'
    | '/admin/'
    | '/products/'
    | '/profile/'
    | '/admin/products/$slug'
    | '/admin/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/track'
    | '/visualizer'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/info/$id'
    | '/order/$id'
    | '/products/$slug'
    | '/profile/addresses'
    | '/profile/orders'
    | '/admin'
    | '/products'
    | '/profile'
    | '/admin/products/$slug'
    | '/admin/products/new'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/track'
    | '/visualizer'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/info/$id'
    | '/order/$id'
    | '/products/$slug'
    | '/profile/addresses'
    | '/profile/orders'
    | '/admin/'
    | '/products/'
    | '/profile/'
    | '/admin/products/$slug'
    | '/admin/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  TrackRoute: typeof TrackRoute
  VisualizerRoute: typeof VisualizerRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  InfoIdRoute: typeof InfoIdRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  ProfileOrdersRoute: typeof ProfileOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  AdminProductsSlugRoute: typeof AdminProductsSlugRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$id': {
      id: '/info/$id'
      path: '/info/$id'
      fullPath: '/info/$id'
      preLoaderRoute: typeof InfoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/profile/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/orders': {
      id: '/profile/orders'
      path: '/profile/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof ProfileOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$slug': {
      id: '/admin/products/$slug'
      path: '/admin/products/$slug'
      fullPath: '/admin/products/$slug'
      preLoaderRoute: typeof AdminProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  TrackRoute: TrackRoute,
  VisualizerRoute: VisualizerRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  InfoIdRoute: InfoIdRoute,
  OrderIdRoute: OrderIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProfileAddressesRoute: ProfileAddressesRoute,
  ProfileOrdersRoute: ProfileOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  AdminProductsSlugRoute: AdminProductsSlugRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
